name: ${pom.name}
description: ${pom.description}
website: ${pom.url}
version: ${pom.version}
author: captbunzo

main: net.nyvaria.openanalytics.OpenAnalytics
softdepend: [Multiverse-Core, SignShop]

commands:
  analytics:
    description: Interact with the OpenAnalytics plugin
    usage: /analytics [command] - Interact with the OpenAnalytics plugin

permissions:
  openanalytics.admin:
    description: Gives access to the /analytics admin commands
  
  openanalytics.optout:
    description: Gives access to the /analytics optout command
