name: ${pom.name}
description: ${pom.description}
website: ${pom.url}
version: ${pom.version}
author: captbunzo

main: net.nyvaria.openanalytics.bukkit.OpenAnalytics
depend: [Vault]
softdepend: [Multiverse-Core, SignShop, zPermission]

commands:
  analytics:
    description: Interact with the OpenAnalytics plugin
    usage: /analytics [command] - Interact with the OpenAnalytics plugin

permissions:
  openanalytics.admin:
    description: Allow a player to use the "/analytics admin" command
  
  openanalytics.optout:
    description: Allow a player to opt out/in using the "/analytics optout" command

  openanalytics.optout.other:
    description: Allow a player to opt out/in other players using the "/analytics optout" command
